image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 5900
- port: 6080
- port: 35900
tasks:
- command: docker --version
  command: docker-compose --version
  command: docker-machine --version
vscode:
  extensions:
    - googlecloudtools.cloudcode@0.0.12:aImviY7NjOmGuXuyoD+uxQ==