image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 5900
- port: 6080
- port: 35900

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- command: docker --version
vscode:
  extensions:
    - googlecloudtools.cloudcode@0.0.12:aImviY7NjOmGuXuyoD+uxQ==
